# Generated by Django 4.1.5 on 2023-03-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_customuser_groups_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ваша почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(
                help_text='Максимальная длина 30 символов',
                max_length=30,
                unique=True,
                verbose_name='имя пользователя',
            ),
        ),
        migrations.AlterField(
            model_name='passwordresetemail',
            name='user_email',
            field=models.EmailField(max_length=254, verbose_name='ваша почта'),
        ),
    ]
