# Generated by Django 4.1.5 on 2023-03-29 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0001_initial'),
        (
            'users',
            '0003_alter_customuser_email_alter_customuser_username_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='feedback_mails',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='feedback',
                to='feedback.feedback',
                verbose_name='письма от пользователя',
            ),
        ),
    ]
