# Generated by Django 4.2 on 2023-04-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_customuser_feedback_mails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(
                max_length=254, unique=True, verbose_name='ваша почта'
            ),
        ),
    ]
