# Generated by Django 4.2 on 2023-04-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(
                blank=True,
                help_text='Введите свою дату рождения',
                null=True,
                verbose_name='дата рождения',
            ),
        ),
    ]
