# Generated by Django 4.1.5 on 2023-01-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='максимальная длина 30 символов', max_length=30, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
