# Generated by Django 4.1.5 on 2023-01-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='previews/%Y/%m/%d', verbose_name='аватарка'),
        ),
    ]
