# Generated by Django 4.1.5 on 2023-01-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='avatar/%Y/%m/%d', verbose_name='добавьте картинку профиля'),
        ),
    ]
