# Generated by Django 4.1.5 on 2023-01-14 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galleries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(help_text='Введите название галереи картин', max_length=50, verbose_name='название галереи')),
                ('gallery_location', models.CharField(help_text='Введите локацию галереи', max_length=75, verbose_name='расположение галереи')),
                ('gallery_slug', models.SlugField(help_text='Введите url адрес для галереи', max_length=55, verbose_name='url галереи')),
                ('gallery_description', models.TextField(help_text='Максимум 1000 символов', max_length=1000, verbose_name='интересные факты о галереи')),
                ('gallery_image', models.ImageField(help_text='Введите путь до изображения галереи', upload_to='galleries/', verbose_name='путь до изображения галереи')),
            ],
            options={
                'verbose_name': 'галерея',
                'verbose_name_plural': 'галереи',
            },
        ),
        migrations.CreateModel(
            name='GalleryPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Выберите путь до фотографии галереи', upload_to='', verbose_name='путь до фотографии галереи')),
                ('gallery_photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.galleries', verbose_name='фотографии галереи')),
            ],
        ),
    ]
