# Generated by Django 4.1.5 on 2023-04-09 12:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('galleries', '0005_rename_gallery_slug_galleries_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artists', '0002_rename_artist_slug_artists_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'painting_name',
                    models.CharField(
                        help_text='Максимум 50 символов',
                        max_length=50,
                        verbose_name='название картины',
                    ),
                ),
                (
                    'painting_creation_year',
                    models.IntegerField(
                        help_text='Введите реальный год создания картины',
                        validators=[
                            django.core.validators.MinValueValidator(800),
                            django.core.validators.MaxValueValidator(2023),
                        ],
                        verbose_name='год создания картины',
                    ),
                ),
                (
                    'painting_width',
                    models.FloatField(
                        help_text='Введите ширину картины',
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name='ширина картины',
                    ),
                ),
                (
                    'painting_height',
                    models.FloatField(
                        help_text='Введите высоту картины',
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name='высота картины',
                    ),
                ),
                (
                    'painting_materials',
                    models.CharField(
                        help_text='Введите материала, которые использовались при создании картины',
                        max_length=25,
                        verbose_name='материалы картины',
                    ),
                ),
                (
                    'painting_description',
                    models.TextField(
                        help_text='Напишите описание к картине',
                        max_length=1000,
                        verbose_name='описание картины',
                    ),
                ),
                (
                    'painting_photo',
                    models.ImageField(
                        help_text='Введите путь до изображения картины',
                        upload_to='picture/',
                        verbose_name='путь до изображения картины',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        help_text='Введите url адрес для картины',
                        max_length=55,
                        verbose_name='слаг картины',
                    ),
                ),
                (
                    'likes',
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='лайк',
                    ),
                ),
                (
                    'painting_artist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='artists',
                        to='artists.artists',
                        verbose_name='художник',
                    ),
                ),
                (
                    'painting_gallery',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='galleries',
                        to='galleries.galleries',
                        verbose_name='галерея',
                    ),
                ),
            ],
            options={
                'verbose_name': 'картина',
                'verbose_name_plural': 'картины',
            },
        ),
    ]
