# Generated by Django 4.1.5 on 2023-04-09 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='painting_slug',
            new_name='slug',
        ),
    ]
