# Generated by Django 4.2 on 2023-04-10 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='painting_description',
        ),
        migrations.AlterField(
            model_name='painting',
            name='slug',
            field=models.SlugField(
                help_text='Введите url адрес для картины',
                max_length=55,
                unique=True,
                verbose_name='слаг картины',
            ),
        ),
        migrations.CreateModel(
            name='PaintingFacts',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'fact',
                    models.TextField(
                        help_text='Максимум 500 символов',
                        max_length=500,
                        verbose_name='факт о картине',
                    ),
                ),
                (
                    'painting',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='painting_facts',
                        to='paintings.painting',
                    ),
                ),
            ],
            options={
                'verbose_name': 'факт о картине',
                'verbose_name_plural': 'факты о картине',
            },
        ),
    ]
