# Generated by Django 4.1.5 on 2023-01-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('paintings', '0002_painting_likes_alter_painting_painting_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='painting_materials',
            field=models.CharField(
                blank=True,
                help_text='введите материала, которые использовались при'
                'создании картины',
                max_length=25,
                verbose_name='материалы картины',
            ),
        ),
    ]
