# Generated by Django 4.2 on 2023-04-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('paintings', '0002_remove_painting_painting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingfacts',
            name='title',
            field=models.CharField(
                blank=True,
                help_text='Напишите заголовок карточки факта',
                max_length=100,
                null=True,
                verbose_name='заголовок',
            ),
        ),
    ]
