# Generated by Django 4.1.5 on 2023-03-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('paintings', '0005_alter_painting_painting_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='painting_materials',
            field=models.CharField(
                help_text='Введите материала, которые использовались при создании картины',
                max_length=25,
                verbose_name='материалы картины',
            ),
        ),
        migrations.AlterField(
            model_name='painting',
            name='painting_photo',
            field=models.ImageField(
                help_text='Введите путь до изображения картины',
                upload_to='picture/',
                verbose_name='путь до изображения картины',
            ),
        ),
    ]
