# Generated by Django 4.1.5 on 2023-04-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('paintings', '0006_alter_painting_painting_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='painting_slug',
            field=models.SlugField(
                help_text='Введите url адрес для картины',
                max_length=55,
                verbose_name='слаг картины',
            ),
        ),
    ]
