# Generated by Django 4.1.5 on 2023-01-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='введите свое имя')),
                ('mail', models.EmailField(help_text='Максимум 150 символов', max_length=150, verbose_name='введите свою почту')),
                ('feedback_text', models.CharField(help_text='Максимум 1000 символов', max_length=1000, verbose_name='ваш отзыв')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
        ),
    ]
