# Generated by Django 4.1.5 on 2023-03-12 10:22

import artists.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='artist',
            field=models.CharField(
                help_text='Введите фамилию, имя и отчество художника через пробел',
                max_length=50,
                validators=[artists.validators.ArtistNameValidator()],
                verbose_name='фИО художника',
            ),
        ),
        migrations.AlterField(
            model_name='artists',
            name='artist_photo',
            field=models.ImageField(
                help_text='Выберите путь до фотографии художника',
                upload_to='artists/',
                verbose_name='путь до фотографии художника',
            ),
        ),
    ]
