# Generated by Django 4.1.5 on 2023-04-09 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='artist_slug',
            new_name='slug',
        ),
    ]
