# Generated by Django 4.2 on 2023-04-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('artists', '0002_rename_artist_slug_artists_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='slug',
            field=models.SlugField(
                help_text='Введите url адрес для художника',
                max_length=55,
                unique=True,
                verbose_name='слаг художника',
            ),
        ),
    ]
