# Generated by Django 4.1.5 on 2023-04-07 14:56

import artists.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('artists', '0002_alter_artists_artist_alter_artists_artist_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artists',
            name='years_of_life',
        ),
        migrations.AddField(
            model_name='artists',
            name='birth_date',
            field=models.IntegerField(
                help_text='Введите дату рождения художника',
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(800),
                    django.core.validators.MinValueValidator(2023),
                ],
                verbose_name='дата рождения художника',
            ),
        ),
        migrations.AddField(
            model_name='artists',
            name='death_date',
            field=models.IntegerField(
                help_text='Введите дату сметри художника',
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(800),
                    django.core.validators.MinValueValidator(2023),
                ],
                verbose_name='дата смерти художника',
            ),
        ),
        migrations.AlterField(
            model_name='artists',
            name='artist',
            field=models.CharField(
                help_text='Введите фамилию, имя и отчество художника через пробел',
                max_length=50,
                validators=[artists.validators.ArtistNameValidator()],
                verbose_name='ФИО художника',
            ),
        ),
        migrations.AlterField(
            model_name='artists',
            name='artist_slug',
            field=models.SlugField(
                help_text='Введите url адрес для художника',
                max_length=55,
                verbose_name='слаг художника',
            ),
        ),
    ]
