# Generated by Django 4.1.5 on 2023-04-07 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'artists',
            '0003_remove_artists_years_of_life_artists_birth_date_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='alived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artists',
            name='birth_date',
            field=models.IntegerField(
                blank=True,
                help_text='Введите дату рождения художника',
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(800),
                    django.core.validators.MaxValueValidator(2023),
                ],
                verbose_name='дата рождения художника',
            ),
        ),
        migrations.AlterField(
            model_name='artists',
            name='death_date',
            field=models.CharField(
                blank=True,
                help_text='Введите дату сметри художника',
                max_length=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(800),
                    django.core.validators.MaxValueValidator(2023),
                ],
                verbose_name='дата смерти художника',
            ),
        ),
    ]
