# Generated by Django 4.1.5 on 2023-04-07 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('artists', '0004_artists_alived_alter_artists_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='alived',
            field=models.BooleanField(
                default=False,
                help_text='Поставьте галочку, если художник жив до сих пор',
                verbose_name='жив ли сейчас',
            ),
        ),
        migrations.AlterField(
            model_name='artists',
            name='death_date',
            field=models.IntegerField(
                blank=True,
                help_text='Введите дату сметри художника',
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(800),
                    django.core.validators.MaxValueValidator(2023),
                ],
                verbose_name='дата смерти художника',
            ),
        ),
    ]
