# Generated by Django 4.1.5 on 2023-01-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphotos',
            name='photo',
            field=models.ImageField(
                help_text='Выберите путь до фотографии галереи',
                upload_to='galleries/',
                verbose_name='путь до фотографии галереи',
            ),
        ),
    ]
