# Generated by Django 4.1.5 on 2023-04-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('galleries', '0003_alter_galleryphotos_gallery_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleries',
            name='gallery_description',
            field=models.TextField(
                help_text='Максимум 1000 символов',
                max_length=1000,
                verbose_name='описание галереи',
            ),
        ),
        migrations.AlterField(
            model_name='galleries',
            name='gallery_slug',
            field=models.SlugField(
                help_text='Введите url адрес для галереи',
                max_length=55,
                verbose_name='слаг галереи',
            ),
        ),
    ]
