# Generated by Django 4.1.5 on 2023-04-09 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('galleries', '0004_alter_galleries_gallery_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleries',
            old_name='gallery_slug',
            new_name='slug',
        ),
    ]
