# Generated by Django 4.2 on 2023-04-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('galleries', '0005_rename_gallery_slug_galleries_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleries',
            name='gallery_name',
            field=models.CharField(
                help_text='Введите название галереи картин',
                max_length=50,
                unique=True,
                verbose_name='название галереи',
            ),
        ),
        migrations.AlterField(
            model_name='galleries',
            name='slug',
            field=models.SlugField(
                help_text='Введите url адрес для галереи',
                max_length=55,
                unique=True,
                verbose_name='слаг галереи',
            ),
        ),
    ]
