# Generated by Django 4.1.5 on 2023-03-29 20:36

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Максимум 150 символов',
                        max_length=150,
                        verbose_name='введите свое имя',
                    ),
                ),
                (
                    'mail',
                    models.EmailField(
                        help_text='Максимум 150 символов',
                        max_length=150,
                        verbose_name='введите свою почту',
                    ),
                ),
                (
                    'feedback_text',
                    models.CharField(
                        help_text='Максимум 1000 символов',
                        max_length=1000,
                        verbose_name='ваш отзыв',
                    ),
                ),
                (
                    'created_on',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='дата создания'
                    ),
                ),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.CreateModel(
            name='FeedbackFiles',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        upload_to=feedback.models.FeedbackFiles.get_path,
                        verbose_name='файл',
                    ),
                ),
                (
                    'feedback',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files',
                        to='feedback.feedback',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'файлы, приложенные к отзыву',
            },
        ),
    ]
