# Generated by Django 4.1.5 on 2023-04-07 14:56

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackfiles',
            options={
                'verbose_name': 'файл, приложенный к отзыву',
                'verbose_name_plural': 'файлы, приложенные к отзыву',
            },
        ),
        migrations.AlterField(
            model_name='feedbackfiles',
            name='file',
            field=models.FileField(
                blank=True,
                help_text='Прикрепите файлы к отзыву',
                upload_to=feedback.models.FeedbackFiles.get_path,
                verbose_name='файлы',
            ),
        ),
    ]
