# Generated by Django 4.1.5 on 2023-04-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'feedback',
            '0002_alter_feedbackfiles_options_alter_feedbackfiles_file',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mail',
            field=models.EmailField(
                help_text='Максимум 150 символов',
                max_length=150,
                verbose_name='почта',
            ),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(
                help_text='Максимум 150 символов',
                max_length=150,
                verbose_name='имя',
            ),
        ),
    ]
