# Generated by Django 4.1.5 on 2023-03-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0003_feedbackfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='files',
            field=models.FileField(
                blank=True, upload_to='', verbose_name='Файлы'
            ),
        ),
        migrations.DeleteModel(
            name='FeedbackFiles',
        ),
    ]
