# Generated by Django 4.1.5 on 2023-03-27 21:00

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0004_feedback_files_delete_feedbackfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='files',
            field=models.FileField(
                blank=True,
                help_text='Приложите файлы к отзыву',
                upload_to=feedback.models.Feedback.get_path,
                verbose_name='файлы',
            ),
        ),
    ]
