# Generated by Django 4.1.5 on 2023-03-27 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0005_alter_feedback_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='files',
            field=models.FileField(
                blank=True,
                help_text='Приложите файлы к отзыву',
                upload_to='',
                verbose_name='файлы',
            ),
        ),
        migrations.CreateModel(
            name='FeedbackFiles',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(blank=True, null=True, upload_to=''),
                ),
                (
                    'feedback',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feedback_files',
                        to='feedback.feedback',
                    ),
                ),
            ],
        ),
    ]
