# Generated by Django 4.1.5 on 2023-01-14 10:46

import artists.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(help_text='Введите фамилию, имя и отчество художника через пробел', max_length=50, validators=[artists.validators.ArtistNameValidator()], verbose_name='ФИО художника')),
                ('years_of_life', models.CharField(help_text='Введите год рождения и смерти художника через тире. Пример: 1899-1977', max_length=10, validators=[artists.validators.ArtistYearsValidator()], verbose_name='годы жизни')),
                ('short_biography', models.TextField(help_text='Максимум 1000 символов', max_length=1000, verbose_name='краткая биография')),
                ('artist_photo', models.ImageField(help_text='выберите путь до фотографии художника', upload_to='artists/', verbose_name='путь до фотографии художника')),
                ('artist_slug', models.SlugField(help_text='Введите url адрес для художника', max_length=55, verbose_name='url художника')),
            ],
            options={
                'verbose_name': 'художник',
                'verbose_name_plural': 'художники',
            },
        ),
    ]
