# Generated by Django 4.1.5 on 2023-01-14 10:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import paintings.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_name', models.CharField(help_text='Максимум 50 символов', max_length=50, verbose_name='название картины')),
                ('painting_creation_year', models.IntegerField(help_text='Введите реальный год создания картины', validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(2022)], verbose_name='год создания картины')),
                ('painting_size', models.CharField(help_text='Введите размер картины через x', max_length=10, validators=[paintings.validators.SizeValidation()], verbose_name='введите размер картины')),
                ('painting_description', models.TextField(help_text='Напишите описание к картине', max_length=1000, verbose_name='описание картины')),
                ('painting_photo', models.ImageField(help_text='введите путь до изображения картины', upload_to='picture/', verbose_name='путь до изображения картины')),
                ('painting_slug', models.SlugField(help_text='Введите url адрес для картины', max_length=55, verbose_name='url картины')),
                ('painting_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='artists.artists', verbose_name='художник')),
                ('painting_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='galleries.galleries', verbose_name='галерея')),
            ],
            options={
                'verbose_name': 'картина',
                'verbose_name_plural': 'картины',
            },
        ),
    ]
